site_name: OctoTrack
site_url: https://JKG-cpu.github.io/OctoTrack/
repo_url: https://github.com/JKG-cpu/OctoTrack

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - search.suggest
    - navigation.expand

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - GitHub Auth Token: authtoken.md
  - OctoTrack Setup: setup.md
  - Commands:
    - Running Your First Command: commands/first_command.md
  # - Commands:
  #   - Setup: commands/setup.md
  #   - Config: commands/config.md
  #   - Repository: commands/repo.md
  #   - Commits: commands/commits.md