site_name: OctoTrack
site_url: https://JKG-cpu.github.io/OctoTrack/
repo_url: https://github.com/JKG-cpu/OctoTrack

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - search.suggest
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md